sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '0.13'
  - 'iojs'
before_install:
  - npm install -g gulp
before_script:
  - gulp build
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '0.13'
notifications:
  email:
    on_success: never
    on_failure: always
