sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - npm install -g gulp
before_script:
  - gulp build
notifications:
  email:
    on_success: never
    on_failure: always
